baseURL = "https://eloymelo.com/"
title = "Eloy Melo"
theme = "PaperMod"
enableRobotsTXT = true
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[pagination]
  pagerSize = 10

  [languages.en]
    languageName = "English"
    languageCode = "en-US"
    weight = 2
    title = "Eloy Melo"
    
    [languages.en.params]
      author = "Eloy Melo"
      description = "IT Professional Transitioning to Backend Development"
      showReadingTime = true
      defaultTheme = "auto"
      ShowShareButtons = false
      ShowPostNavLinks = true
      ShowBreadCrumbs = true
      ShowCodeCopyButtons = true
      ShowDate = true
      DisableRelativeTime = true
      DateFormat = "2 January 2006"
    
    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Posts"
      url = "/posts/"
      weight = 2
    [[languages.en.menu.main]]
      name = "Projects"
      url = "/projects/"
      weight = 3
    [[languages.en.menu.main]]
      name = "Tutorials"
      url = "/tutorials/"
      weight = 4
    [[languages.en.menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 5